version: '3'
services:
  database:
    image: mongo:4.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: realestate
    volumes:
      - ./dump/realestate:/dump/realestate-listing
      - ./server/data:/dump/scripts
      - ../mongo-data:/data/db
    ports:
      - '27017-27019:27017-27019'
  web:
    build: .
    image: realworldio/realestate-angularjs
    environment:
      MONGODB_URI: mongodb://root:example@database/realestate
    depends_on:
      - database
    ports:
      - 8080:5000